[tool.qpro]
[[tool.qpro.server_targets]]
user = ""
host = ""
path = ""
port = "22"

[tool.qpro.config]
build = "javac -d dist main.java"
entry_point = "main.java"
executable = "java -classpath dist QproJavaTemplate"
input_file = "dist/input.txt"
template_root = "template/"
